captainVersion: 4
services:
  ollama:
    build: .
    container_name: ollama
    image: ollama/ollama
    healthcheck:
      test: ollama --version || exit 1
      interval: 10s
    ports:
      - "11434:11434"
    volumes:
      - $$cap_appname-ollama-data:/root/.ollama
volumes:
  $$cap_appname-ollama-data:

caproverOneClickApp:
    instructions:
        start: |-
            Ollama is currently being set up.
        end: |-
            Ollama has been deployed! Try connecting to it with the Python Client. 
    displayName: Ollama
    isOfficial: true
    description: Ollama running locally in CapRover
    documentation: https://ollama.com
